// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJuOIViL7a1WW6EuRP2ByV0an7UeHaiKU',
    appId: '1:908666865982:web:0e060b1a350b03811fc46f',
    messagingSenderId: '908666865982',
    projectId: 'office-market-27ec0',
    authDomain: 'office-market-27ec0.firebaseapp.com',
    databaseURL: 'https://office-market-27ec0.firebaseio.com',
    storageBucket: 'office-market-27ec0.firebasestorage.app',
    measurementId: 'G-QV61BS0TVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuHLrBKy8w3prSax-W1ezdwTU4ZlTXMig',
    appId: '1:908666865982:android:45ed39b00484b3aa1fc46f',
    messagingSenderId: '908666865982',
    projectId: 'office-market-27ec0',
    databaseURL: 'https://office-market-27ec0.firebaseio.com',
    storageBucket: 'office-market-27ec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKA7dkS8PMDcPrD94WTZj9bSzb6t5AXBM',
    appId: '1:908666865982:ios:81998d0041ba34631fc46f',
    messagingSenderId: '908666865982',
    projectId: 'office-market-27ec0',
    databaseURL: 'https://office-market-27ec0.firebaseio.com',
    storageBucket: 'office-market-27ec0.firebasestorage.app',
    iosClientId: '908666865982-13k7t0sblrs8af0rmuq6s02tra62oh03.apps.googleusercontent.com',
    iosBundleId: 'com.recipewallet.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKA7dkS8PMDcPrD94WTZj9bSzb6t5AXBM',
    appId: '1:908666865982:ios:81998d0041ba34631fc46f',
    messagingSenderId: '908666865982',
    projectId: 'office-market-27ec0',
    databaseURL: 'https://office-market-27ec0.firebaseio.com',
    storageBucket: 'office-market-27ec0.firebasestorage.app',
    iosClientId: '908666865982-13k7t0sblrs8af0rmuq6s02tra62oh03.apps.googleusercontent.com',
    iosBundleId: 'com.recipewallet.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYO9gQmc5N23SM87yfIJgy23FhRDfC1MQ',
    appId: '1:908666865982:web:1e22a0f0014b04d81fc46f',
    messagingSenderId: '908666865982',
    projectId: 'office-market-27ec0',
    authDomain: 'office-market-27ec0.firebaseapp.com',
    databaseURL: 'https://office-market-27ec0.firebaseio.com',
    storageBucket: 'office-market-27ec0.firebasestorage.app',
    measurementId: 'G-WGBVTC43L4',
  );
}
